# Generated by Django 5.1.6 on 2025-02-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslate', '0002_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
