# Generated by Django 5.1.6 on 2025-02-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traslate', '0003_customuser_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date',
        ),
    ]
