# Generated by Django 5.1.6 on 2025-02-21 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslate', '0004_remove_customuser_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
